name: Sync upstream tags

on:
  schedule:
  - cron: '20 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mirror upstream tags
        run: |
          set -euo pipefail

          upstream_repo="https://github.com/mem0ai/mem0.git"

          # Fetch upstream tags into a separate namespace to avoid polluting local refs/tags
          git fetch --quiet "$upstream_repo" "+refs/tags/*:refs/upstream-tags/*"

          # Pick the latest 'v*' tag by creation time (works for annotated and lightweight tags)
          latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname:strip=2)' refs/upstream-tags/v* | head -n1 || true)
          if [ -z "${latest_tag}" ]; then
            echo "No upstream v* tags found"
            exit 0
          fi

          # If already present locally, nothing to do
          if git rev-parse -q --verify "refs/tags/${latest_tag}" >/dev/null; then
            echo "Latest upstream tag '${latest_tag}' already exists locally"
            exit 0
          fi

          echo "Creating and pushing latest tag: ${latest_tag}"
          git tag "${latest_tag}"
          git push origin "refs/tags/${latest_tag}"
          echo "Done."
