name: Sync upstream tags

on:
  schedule:
  - cron: '20 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync latest v* tag from source
        shell: bash
        run: |
          set -e
          SOURCE_REPO=mem0ai/mem0

          LATEST_TAG=$(git ls-remote --tags --refs https://github.com/${SOURCE_REPO}.git 'v*' \
            | awk '{print $2}' \
            | sed 's#.*/##' \
            | sort -V \
            | tail -n1)

          [ -n "$LATEST_TAG" ] || { echo "No v* tags found upstream"; exit 0; }

          if git ls-remote --tags origin "refs/tags/${LATEST_TAG}" | grep -q "${LATEST_TAG}$"; then
            echo "Tag ${LATEST_TAG} already exists; skipping"
            exit 0
          fi

          git tag "${LATEST_TAG}"
          git push origin "refs/tags/${LATEST_TAG}"
